from enum import IntEnum, auto


class GUIEvent(IntEnum):
    LEFTMOUSEDOWN = auto()
    RIGHTMOUSEDOWN = auto()
    VIDEORESIZE = auto()
    TEXTINPUT = auto()
    TEXTERASE = auto()
    TEXTCURSORLEFT = auto()
    TEXTCURSORRIGHT = auto()
    RETURN = auto()
    LINEUP = auto()
    LINEDOWN = auto()
    SELECTWORD = auto()
    MOVEBYWORDLEFT = auto()
    MOVEBYWORDRIGHT = auto()
    RESIZEDOWN = auto()
    RESIZEUP = auto()
    DROPFILE = auto()
    WHEEL = auto()
    SEARCHFILE = auto()
    OPENFILE = auto()
    SAVEFILE = auto()
    GOBACKSCREEN = auto()
    TRANSITIONNORMAL = auto()
    TRANSITIONINSERT = auto()
    FONTRESIZE = auto()
    RIGHTKEY = auto()
    LEFTKEY = auto()
